config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  root 'home#index'
  resources :listings
  resources :categories
  resources :messages
  # get 'messages/new/listing_id/user_id/', to: 'messages#new', as: 'reply_message'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  resourcify
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :check_auth

  # GET /messages or /messages.json
  def index
    user_id = current_user.id
    listings = Listing.where(user_id:).all

    listing_ids = listings.map { |item| item.id }

    recived_message = Message.where(listing_id: listing_ids).all

    @recived_message_grouped = recived_message.group_by { |item| item.listing_id.to_s + '-' + item.user_id.to_s }

    sent_message = Message.where(user_id:).all
    @sent_message_grouped = sent_message.group_by { |item| item.listing_id.to_s + '-' + item.user_id.to_s }
  end

  # GET /messages/1 or /messages/1.json
  def show; end

  # GET /messages/new
  def new
    @listing_id = request.query_parameters && request.query_parameters['listing']
    @user_id = request.query_parameters && request.query_parameters['user']

    # redirect_to messages_path if @listing_id && @user_id

    @listing = Listing.find(@listing_id)
    @is_response = @listing && @listing.user_id == current_user.id

    @histroy_messages = Message.where(listing_id: @listing_id, user_id: @user_id).all

    @message = Message.new
  end

  # GET /messages/1/edit
  def edit; end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).permit(:text, :is_response, :user_id, :listing_id)
  end

  def check_auth
    authorize Message
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.text_field:text  %>
    <%= form.submit 'send message' %>
  </div>
  <div style="display: none">
    <%= form.check_box :is_response, checked:@is_response  %>
  </div>
  <div  style="display: none">
    <%= form.text_field :user_id, value:@user_id %>
  </div>
  <div style="display: none">
    <%= form.text_field :listing_id, value:@listing_id  %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong><%= message.is_response ? 'Response' : 'Text' %>:</strong>
    <%= message.text %>
  </p>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Messages</h1>
<div id="messages" class="container-fluid mb-2">
  <div class="row">
    <h3> Enquires For My Listing </h3>
      <% @recived_message_grouped.each do |listing, messages| %>
        <div class="bg-secondary p-2 text-dark bg-opacity-10 mb-2">
          <p>
            <strong>Sent from User:</strong>
            <%= User.find(messages[0].user_id).email %>
            <strong>for my listing: </strong><%= link_to Listing.find(messages[0].listing_id).name, Listing.find(messages[0].listing_id) %>
            <strong>Listing key: </strong><%= listing %>
          </p>
          <% messages.each do |message| %>
            <%= render message %>
          <% end %>
            <a href="/messages/new?listing=<%= messages[0].listing_id %>&user=<%= messages[0].user_id %>"> Reply </a>
        </div>
    <% end %> 
  </div>
</div>
<div id="messages" class="container-fluid">
  <div class="row">
    <h3> Want To Buy </h3>
    <% @sent_message_grouped.each do |key, messages| %>
      <div class="bg-secondary p-2 text-dark bg-opacity-10 mb-2">
        <p>
        <strong>Listing name: </strong><%= link_to Listing.find(messages[0].listing_id).name, Listing.find(messages[0].listing_id) %>
        </p>
        <% messages.each do |message| %>
          <%= render message %>
        <% end %>
        <div>
          <a href="/messages/new?listing=<%= messages[0].listing_id %>&user=<%= messages[0].user_id %>"> Send message to seller </a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/new.html.erb
<h1>Message for <%= link_to @listing.name, @listing %></h1>
<br>
<%# display the histroy message with dialogue format %>
<div class="container-fluid">
  <% @histroy_messages.each do |histroy_message| %>
  <div class="row">
    <% if histroy_message.is_response %>
      <div class="text-end bg-success p-2 text-dark bg-opacity-25 mb-2 rounded-2 col-md-4 ms-auto" style="width: 30vw;">
        <%= histroy_message.text %>
      </div>
    <% else %>
      <div class="bg-secondary p-2 text-dark bg-opacity-25 mb-2 rounded-2 col-md-4" style="width: 30vw;">
        <%= histroy_message.text %>
      </div>
    <% end %>
  </div>
  <% end %>
</div>
<div class="container-fluid my-2">
<%= render "form", message: @message %>
<%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>