config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  root 'home#index'
  resources :listings
  resources :categories
  resources :messages
  # get 'messages/new/listing_id/user_id/', to: 'messages#new', as: 'reply_message'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :messages, dependent: :destroy
    resourcify
    has_one_attached :picture
    validates :name, presence: true
    validates :price, numericality: { greater_than_orequal_to: 0 }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, except: %i[index show]
  before_action :check_auth

  before_action :set_listing, only: %i[show edit update destroy]
  before_action :set_categories, only: %i[new edit]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show; end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit; end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.picture.purge
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
    can_edit(@listing)
  end

  # Only allow a list of trusted parameters through.
  def listing_params
    params.require(:listing).permit(:name, :price, :condition, :category_id, :user_id, :picture)
  end

  def set_categories
    @categories = Category.order(:name)
  end

  def can_edit(listing)
    @can_edit = current_user && current_user.id == listing.user_id
  end
end

  def check_auth
    authorize Listing
  end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>
      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset class="mb-2">
    <div class="mb-2">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
    <div class="mb-2">
      <%= form.label :price, style: "display: block" %>
      <%= form.number_field :price %>
    </div>
    <div class="mb-2">
      <%= form.label :condition, style: "display: block" %>
      <%= form.text_field :condition %>
    </div>
    <div class="d-none">
      <%= form.label :user_id %>
      <%= form.text_field :user_id, value:current_user.id %>
    </div class="mb-2">
    <div class="mb-2">
      <%= form.label :category_id, style: "display: block" %>
      <%= form.collection_select :category_id, @categories, :id, :name %>
    </div>
    <div class="mb-2">
      <% if @listing.picture.attached? %>
        <%= cl_image_tag @listing.picture.key, transformation: ["media_lib_thumb"], cloud_name: 'jimmyboei' %>
      <% else %>
        <%= image_tag("listing_default.png") %>
      <% end %>
    </div>
    <div class="mb-2">
      <%= form.label :picture %>
      <%= form.file_field :picture %>
    </div>
    <div>
      <%= form.submit %>
    </div>
  </fieldset>
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p>
    <strong>Seller:</strong>
    <%= listing.user.email %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= listing.name %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= number_to_currency(listing.price) %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= listing.category.name %>
  </p>
  <p>
    <strong>Condition:</strong>
    <%= listing.condition %>
  </p>
</div>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to 'Show this listing', @listing, class: "btn btn-primary" %> |
  <%= link_to "Back to listings", listings_path, class: "btn btn-info" %>
</div>

app/views/listings/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Listings</h1>
<% if user_signed_in?  %>
  <%= link_to "New listing", new_listing_path, class: "btn btn-primary my-1" %>
<% end %>
<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-4">
      <div class="card my-1" style="width: 18rem;">
        <% if listing.picture.attached? %>
          <%= image_tag listing.picture %>
        <% else %>
           <%= image_tag("listing_default.png") %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= listing.name %></h5>
          <%= number_to_currency(listing.price) %>
          <p class="card-text">  <%= listing.condition %>.</p>
          <%= link_to 'Show this listing', listing, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/show.html.erb
<p style="color: green"><%= notice %></p>
<% if @listing.picture.attached? %>
  <%= image_tag @listing.picture %>
<% else %>
  <%= image_tag("listing_default.png") %>
<% end %>
<%= render @listing %>
<div>
  <% if @can_edit %>
    <%= link_to "Edit this listing", edit_listing_path(@listing), class: "btn btn-warning mb-2" %>
    <%= button_to "Destroy this listing", @listing, class: "btn btn-danger mb-2", method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete '#{@listing.name}'?" } } %>
  <% end %>
  <% if user_signed_in? && !@can_edit %>
    <div>
      <a href="/messages/new?listing=<%=@listing.id%>&user=<%= current_user.id %>" class="btn btn-info my-2"> Send message </a>
    </div>
  <% end %>
  <%= link_to "Back to listings", listings_path, class: "btn btn-primary" %>
</div>