config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  root 'home#index'
  resources :listings
  resources :categories
  resources :messages
  # get 'messages/new/listing_id/user_id/', to: 'messages#new', as: 'reply_message'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rise Apartment Marketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Rise Apartment Marketplace</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Listings', listings_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Messages', messages_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? && policy(:category).index? %>
              <li class="nav-item">
                <%= link_to 'Categories', categories_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <ul class= "navbar-nav ml-auto">
              <li class="nav-item p-1">
                Welcome, <%= current_user.email%>
              </li>
              <li class="nav-item">
                <%= button_to 'Logout', destroy_user_session_path, class: 'btn btn-primary', method: :delete %>
              </li>
            </ul>
          <% else %>
            <ul class= "navbar-nav ml-auto">
              <li class="nav-item p-1">
                <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-secondary'%>
              </li>
              <li class="nav-item p-1">
                <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    <main class="p-3">
      <% if notice %>
        <p class="alert alert-info notice" role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger notice" role="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </body>
  </html>